function (fooyin_print_summary)
  message(STATUS "")
  message(STATUS "******** Fooyin Configuration ********")
  message(STATUS "General:")
  message(STATUS "  Fooyin version        : ${FOOYIN_VERSION}")
  message(STATUS "  CMake version         : ${CMAKE_VERSION}")
  message(STATUS "  CMake command         : ${CMAKE_COMMAND}")
  message(STATUS "  System                : ${CMAKE_SYSTEM_NAME}")
  message(STATUS "  C++ compiler          : ${CMAKE_CXX_COMPILER}")
  message(STATUS "  C++ compiler version  : ${CMAKE_CXX_COMPILER_VERSION}")
  message(STATUS "  CXX flags             : ${CMAKE_CXX_FLAGS}")
  message(STATUS "  Build type            : ${CMAKE_BUILD_TYPE}")
  message(STATUS "")
  message(STATUS "Install location:")
  message(STATUS "  Install prefix        : ${CMAKE_INSTALL_PREFIX}")
  message(STATUS "  Binary install dir    : ${FOOYIN_BIN_INSTALL_DIR}")
  message(STATUS "  Library install dir   : ${FOOYIN_LIBRARY_INSTALL_DIR}")
  message(STATUS "  Plugin install dir    : ${FOOYIN_PLUGIN_INSTALL_DIR}")
  message(STATUS "")
endfunction()
