include(GNUInstallDirs)

set(FOOYIN_BINARY_DIR ${CMAKE_INSTALL_BINDIR})
set(FOOYIN_LIBRARY_DIR "${CMAKE_INSTALL_LIBDIR}")
set(FOOYIN_PLUGIN_DIR "${FOOYIN_LIBRARY_DIR}/fooyin")

set(FOOYIN_LIBRARY_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/${FOOYIN_LIBRARY_DIR})
set(FOOYIN_PLUGIN_INSTALL_PATH ${CMAKE_INSTALL_PREFIX}/${FOOYIN_PLUGIN_DIR})

set(FOOYIN_BINARY_OUTPUT_DIR ${PROJECT_BINARY_DIR}/${FOOYIN_BINARY_DIR})
set(FOOYIN_LIBRARY_OUTPUT_DIR ${PROJECT_BINARY_DIR}/${FOOYIN_LIBRARY_DIR})
set(FOOYIN_PLUGIN_OUTPUT_DIR ${PROJECT_BINARY_DIR}/${FOOYIN_PLUGIN_DIR})

function(fooyin_option option description)
  set(option_arguments ${ARGN})
  option(${option} "${description}" ${option_arguments})
  add_feature_info("Option ${option}" ${option} "${description}")
endfunction()

if(FOOYIN_STATIC)
  set(FOOYIN_LIBRARY_TYPE STATIC)
  set(FOOYIN_PLUGIN_TYPE STATIC)
else()
  set(FOOYIN_LIBRARY_TYPE SHARED)
  set(FOOYIN_PLUGIN_TYPE MODULE)
endif()
