name: Build FreeBSD

on:
  workflow_call:
    inputs:
      version_suffix:
        required: false
        type: string
        default: ''

env:
  FOOYIN_VERSION_SUFFIX: ${{ inputs.version_suffix }}
  BUILD_TESTS: ON
  BUILD_CCACHE: OFF

jobs:
  freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    env:
      FREEBSD_VERSION: '15.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Start FreeBSD VM
        uses: cross-platform-actions/action@v1.4.0
        with:
          operating_system: freebsd
          architecture: x86-64
          cpu_count: 4
          shell: bash
          version: ${{ env.FREEBSD_VERSION }}
          environment_variables: BUILD_TESTS BUILD_CCACHE FOOYIN_VERSION_SUFFIX

      - name: Build and test
        shell: cpa.sh {0}
        run: |
          ./ci/freebsd-depends.sh
          ./ci/freebsd-build.sh
          if [ "$BUILD_TESTS" = "ON" ]; then
            ./ci/tests.sh
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: freebsd-${{ env.FREEBSD_VERSION }}
          path: pkg
