name: Build Windows

on:
  workflow_call:

env:
  QT_VERSION: '6.8.3'
  VCPKG_DISABLE_METRICS: true

jobs:
  windows:
    name: Windows
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: windows-latest
            qt-arch: win64_msvc2022_64
            msvc-arch: amd64
            triplet: x64-windows
            cmake-preset: release-vcpkg
          - arch: arm64
            runner: windows-11-arm
            qt-arch: win64_msvc2022_arm64
            msvc-arch: arm64
            triplet: arm64-windows
            cmake-preset: release-vcpkg-arm64
    runs-on: ${{ matrix.runner }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install CMake
        uses: lukka/get-cmake@latest

      - name: Install dependencies
        run: choco install ninja nsis -y

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          archives: qtbase qtsvg qttools
          cache: true
          arch: ${{ matrix.qt-arch }}
          install-deps: 'true'

      - name: Setup MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.msvc-arch }}

      - name: Setup vcpkg cache
        shell: pwsh
        run: |
          $cacheDir = "${{ github.workspace }}/vcpkg-binary-cache"
          New-Item -ItemType Directory -Force -Path $cacheDir
          echo "VCPKG_BINARY_SOURCES=clear;files,$cacheDir,readwrite" >> $env:GITHUB_ENV
          echo "VCPKG_TARGET_TRIPLET=${{ matrix.triplet }}" >> $env:GITHUB_ENV

      - name: Cache vcpkg
        uses: actions/cache@v5
        with:
          path: |
            ${{ github.workspace }}/vcpkg-binary-cache
            build-${{ matrix.cmake-preset }}_installed
          key: ${{ runner.os }}-vcpkg-${{ matrix.cmake-preset }}-${{ hashFiles('**/vcpkg.json', '**/vcpkg-configuration.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-${{ matrix.cmake-preset }}-
            ${{ runner.os }}-vcpkg-

      - name: Set CMAKE_PRESET
        shell: pwsh
        run: echo "CMAKE_PRESET=${{ matrix.cmake-preset }}" >> $env:GITHUB_ENV

      - name: Build & Package
        run: .\ci\windows-build.ps1
        shell: pwsh

      - name: Upload installer artifact
        uses: actions/upload-artifact@v6
        with:
          name: windows-setup-${{ matrix.arch }}
          path: artifacts/*.exe

      - name: Upload portable artifact
        uses: actions/upload-artifact@v6
        with:
          name: windows-portable-${{ matrix.arch }}
          path: artifacts/*.zip
