name: Build FreeBSD

on:
  workflow_call:

env:
  BUILD_TESTS: ON
  CCACHE_DIR: ${{ github.workspace }}/.ccache
  CCACHE_BASEDIR: ${{ github.workspace }}
  CCACHE_MAXSIZE: 1G
  CCACHE_COMPILERCHECK: content
  CCACHE_SLOPPINESS: pch_defines,time_macros

jobs:
  freebsd:
    name: FreeBSD
    runs-on: ubuntu-latest
    env:
      FREEBSD_VERSION: '15.0'
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Cache ccache
        uses: actions/cache@v6
        with:
          path: ${{ env.CCACHE_DIR }}
          key: freebsd-${{ env.FREEBSD_VERSION }}-ccache-${{ github.sha }}
          restore-keys: |
            freebsd-${{ env.FREEBSD_VERSION }}-ccache-

      - name: Start FreeBSD VM
        uses: cross-platform-actions/action@v1.4.0
        with:
          operating_system: freebsd
          architecture: x86-64
          cpu_count: 4
          shell: bash
          version: ${{ env.FREEBSD_VERSION }}
          environment_variables: BUILD_TESTS CCACHE_DIR CCACHE_BASEDIR CCACHE_MAXSIZE CCACHE_COMPILERCHECK CCACHE_SLOPPINESS

      - name: Build and test
        shell: cpa.sh {0}
        run: |
          ./ci/freebsd-depends.sh
          ./ci/freebsd-build.sh
          if [ "$BUILD_TESTS" = "ON" ]; then
            ./ci/tests.sh
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: freebsd-${{ env.FREEBSD_VERSION }}
          path: pkg
