name: Build

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

permissions:
  contents: write # needed for vcpkg cache and release upload

jobs:
  linux:
    name: Build Linux
    uses: ./.github/workflows/build-linux.yml
    secrets: inherit

  freebsd:
    name: Build FreeBSD
    uses: ./.github/workflows/build-freebsd.yml
    secrets: inherit

  windows:
    name: Build Windows
    uses: ./.github/workflows/build-windows.yml
    secrets: inherit

  macos:
    name: Build macOS
    uses: ./.github/workflows/build-macos.yml
    secrets: inherit

  attach:
    name: Attach to release
    if: github.event_name == 'release' && github.event.action == 'published'
    runs-on: ubuntu-latest
    needs:
      - linux
      - freebsd
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download Fedora artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: fedora-*
          path: ./artifacts
          merge-multiple: true

      - name: Download Debian artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: debian-*
          path: ./artifacts
          merge-multiple: true

      - name: Download Ubuntu artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: ubuntu-*
          path: ./artifacts
          merge-multiple: true

      - name: Download FreeBSD artifacts
        uses: actions/download-artifact@v7
        with:
          pattern: freebsd-*
          path: ./artifacts
          merge-multiple: true

      - name: Check artifact files
        run: ls -R ./artifacts

      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.release.tag_name }}
          file: ./artifacts/*
          overwrite: true
          file_glob: true
