name: Build macOS

on:
  workflow_call:

env:
  BUILD_TESTS: ON

jobs:
  macOS:
    name: macOS-${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: amd64
            runs-on: macos-15-intel
          - arch: aarch64
            runs-on: macos-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Dependencies
        run: |
          ./ci/macos-depends.sh

      - name: Build
        run: |
          ./ci/macos-build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: macos-${{ matrix.arch }}
          path: dmg
