name: macOS build

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [published]

env:
  BUILD_TESTS: Off

jobs:
  macos-arm64:
    name: macOS-arm64
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Dependencies
        run: |
          ./ci/macos-depends.sh

      - name: Build
        run: |
          ./ci/macos-build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: txz

  macos-amd64:
    name: macOS-amd64
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Dependencies
        run: |
          ./ci/macos-depends.sh

      - name: Build
        run: |
          ./ci/macos-build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-amd64
          path: txz
